// Generated by CoffeeScript 1.12.7
(function () {
  var $, a, defaultControls, fn, getWebGL, hasWebGL, i, init, len, s, u;

  $ = function (_) {
    return document.getElementById(_);
  };

  window.shop = new bkcore.hexgl.Shop(null);

  init = function (controlType, quality, hud, godmode) {
    var hexGL, progressbar;
    hexGL = new bkcore.hexgl.HexGL({
      document: document,
      width: window.innerWidth,
      height: window.innerHeight,
      container: $('main'),
      overlay: $('overlay'),
      gameover: $('step-5'),
      quality: quality,
      difficulty: 0,
      hud: hud === 1,
      controlType: controlType,
      godmode: godmode,
      track: 'Cityscape',
      user: JSON.parse(localStorage.getItem('user')),
      game: JSON.parse(localStorage.getItem('game'))
    });
    window.hexGL = hexGL;
    console.log('Creating shop...'); // Debug shop creation
    window.shop = new bkcore.hexgl.Shop(hexGL);
    console.log('Shop created'); // Debug shop created

    progressbar = $('progressbar');
    return hexGL.load({
      onLoad: function () {
        console.log('LOADED.');
        hexGL.init();
        $('step-3').style.display = 'none';
        $('step-4').style.display = 'block';
        return hexGL.start();
      },
      onError: function (s) {
        return console.error("Error loading " + s + ".");
      },
      onProgress: function (p, t, n) {
        console.log("LOADED " + t + " : " + n + " ( " + p.loaded + " / " + p.total + " ).");
        return progressbar.style.width = (p.loaded / p.total * 100) + "%";
      }
    });
  };

  u = bkcore.Utils.getURLParameter;

  defaultControls = bkcore.Utils.isTouchDevice() ? 1 : 0;

  s = [['controlType', ['KEYBOARD', 'TOUCH', 'LEAP MOTION CONTROLLER', 'GAMEPAD'], defaultControls, defaultControls, 'Controls: '], ['quality', ['LOW', 'MID', 'HIGH', 'VERY HIGH'], 3, 3, 'Quality: '], ['hud', ['OFF', 'ON'], 1, 1, 'HUD: '], ['godmode', ['OFF', 'ON'], 0, 1, 'Godmode: ']];

  fn = function (a) {
    var e, f, ref;
    a[3] = (ref = u(a[0])) != null ? ref : a[2];
    e = $("s-" + a[0]);
    (f = function () {
      return e.innerHTML = a[4] + a[1][a[3]];
    })();
    return e.onclick = function () {
      return f(a[3] = (a[3] + 1) % a[1].length);
    };
  };
  for (i = 0, len = s.length; i < len; i++) {
    a = s[i];
    fn(a);
  }

  $('step-2').onclick = function () {
    $('step-2').style.display = 'none';
    $('step-3').style.display = 'block';
    return init(s[0][3], s[1][3], s[2][3], s[3][3]);
  };

  $('step-5').onclick = function () {
    return window.location.reload();
  };

  $('s-credits').onclick = function () {
    $('step-1').style.display = 'none';
    return $('credits').style.display = 'block';
  };

  $('credits').onclick = function () {
    $('step-1').style.display = 'block';
    return $('credits').style.display = 'none';
  };

  hasWebGL = function () {
    var canvas, gl;
    gl = null;
    canvas = document.createElement('canvas');
    try {
      gl = canvas.getContext("webgl");
    } catch (error) { }
    if (gl == null) {
      try {
        gl = canvas.getContext("experimental-webgl");
      } catch (error) { }
    }
    return gl != null;
  };

  if (!hasWebGL()) {
    getWebGL = $('start');
    getWebGL.innerHTML = 'WebGL is not supported!';
    getWebGL.onclick = function () {
      return window.location.href = 'http://get.webgl.org/';
    };
  } else {
    $('start').onclick = function () {
      $('step-1').style.display = 'none';
      $('step-2').style.display = 'block';
      return $('step-2').style.backgroundImage = "url(css/help-" + s[0][3] + ".png)";
    };
  }

  $('s-shop').onclick = function (e) {
    console.log('Shop button clicked');
    e.preventDefault();
    e.stopPropagation();

    var shopDialog = document.getElementById('shop-dialog');
    var shopOverlay = document.querySelector('.shop-overlay');

    if (shopDialog && shopOverlay) {
      shopDialog.classList.add('visible');
      shopOverlay.classList.add('visible');
    }
  };

  // document.addEventListener('DOMContentLoaded', function () {
  //   console.log('Initializing load, checking user inner');

  // User class to manage user data
  // class User {
  //   constructor() {
  //     this.username = null;
  //     this.profile = null;
  //     this.wallet = null;
  //     this.level = 1; // Default level
  //     this.coins = 0; // Default coins
  //     this.score = 0; // Default score
  //   }

  //   load() {
  //     const userData = JSON.parse(localStorage.getItem('user'));
  //     if (userData) {
  //       this.username = userData.username;
  //       this.profile = userData.profile;
  //       this.wallet = userData.wallet;
  //       this.level = userData.level;
  //       this.coins = userData.coins;
  //       this.score = userData.score;
  //     }
  //   }

  //   // Save user data to local storage
  //   save() {
  //     localStorage.setItem('user', JSON.stringify(this));
  //   }

  //   // Remove user data from local storage
  //   remove() {
  //     localStorage.removeItem('user');
  //   }
  // }

  // Initialize user
  // let user = new User(); // Default username
  // user.load(); // Load user data

  // Check if user data exists
  // if (!user.username || user.username === 'Guest') {
  //   console.log('No user data, showing login form');
  //   document.getElementById('username-display').classList.remove('visible');
  //   document.getElementById('username-display').style.display = 'none';
  //   // Show login form and show game menu
  //   var loginForm = document.getElementById('login-form');
  //   var loginOverlay = document.querySelector('.login-overlay');
  //   if (loginForm && loginOverlay) {
  //     loginForm.style.display = 'block'; // Ensure the login form is hidden
  //     loginForm.classList.add('visible');
  //     loginOverlay.classList.add('visible');
  //   }

  // } else {
  //   console.log('User data exists, showing game menu', user.username);
  //   // Hide login form and show game menu
  //   var loginForm = document.getElementById('login-form');
  //   var loginOverlay = document.querySelector('.login-overlay');
  //   if (loginForm && loginOverlay) {
  //     loginForm.style.display = 'none'; // Ensure the login form is hidden
  //     loginForm.classList.remove('visible');
  //     loginOverlay.classList.remove('visible');
  //   }
  //   document.getElementById('username-text').textContent = user.username;
  //   document.getElementById('username-display').classList.add('visible');
  //   document.getElementById('username-display').style.display = 'block';
  //   // Update the shop with user coins
  //   if (window.shop) {
  //     window.shop.coins = user.coins;
  //     document.getElementById('coin-count').textContent = user.coins;
  //   }
  // }

  // // Handle login button click
  // $('login-button').onclick = function () {
  //   var usernameElement = document.getElementById('username');
  //   var username = usernameElement ? usernameElement.value : ''; // Check if the element exists
  //   if (username) {
  //     user = new User(username);
  //     user.save(); // Save user data
  //     console.log('User logged in:', user.username);
  //     // Hide login form and show game menu
  //     var loginForm = document.getElementById('login-form');
  //     var loginOverlay = document.querySelector('.login-overlay');
  //     if (loginForm && loginOverlay) {
  //       loginForm.style.display = 'none'; // Ensure the login form is hidden
  //       loginForm.classList.remove('visible');
  //       loginOverlay.classList.remove('visible');
  //     }
  //     document.getElementById('step-1').style.display = 'block'; // Show game menu
  //     document.getElementById('username-display').classList.add('visible');
  //     document.getElementById('username-display').style.display = 'block';
  //     document.getElementById('username-text').textContent = user.username;
  //   }
  // };

  // $('logout-button').onclick = function (e) {
  //   console.log('Logout button clicked');
  //   e.preventDefault();
  //   e.stopPropagation();
  //   document.getElementById('username-display').classList.remove('visible');
  //   document.getElementById('username-display').style.display = 'none';
  //   document.getElementById('username-text').textContent = 'Guest';
  //   // Initialize user
  //   let user = new User('Guest'); // Default username
  //   user.remove();
  //   user.load(); // Load user data
  //   // Check if user data exists
  //   if (!user.username || user.username === 'Guest') {
  //     console.log('No user data, showing login form');
  //     document.getElementById('username-display').classList.remove('visible');
  //     document.getElementById('username-display').style.display = 'none';
  //     // Show login form and show game menu
  //     var loginForm = document.getElementById('login-form');
  //     var loginOverlay = document.querySelector('.login-overlay');
  //     if (loginForm && loginOverlay) {
  //       loginForm.style.display = 'block'; // Ensure the login form is hidden
  //       loginForm.classList.add('visible');
  //       loginOverlay.classList.add('visible');
  //     }
  //   }
  // }

  // // Existing code for handling other events...
  // $('s-shop').onclick = function (e) {
  //   console.log('Shop button clicked');
  //   e.preventDefault();
  //   e.stopPropagation();

  //   var shopDialog = document.getElementById('shop-dialog');
  //   var shopOverlay = document.querySelector('.shop-overlay');

  //   if (shopDialog && shopOverlay) {
  //     shopDialog.classList.add('visible');
  //     shopOverlay.classList.add('visible');
  //   }
  // };
  // });

}).call(this);
